### ISSUE TITLE
cyclone is missing

### ISSUE THREAD

**Issue by amirouche** [schemedoc/implementation-metadata#3]
http://justinethier.github.io/cyclone/

**Comment by lassik** [comment]
Thanks. Do you have time to make a PR? E.g. copy and edit `chicken.scm` which is quite full featured.

**Comment by justinethier** [comment]
@lassik - Here is a first-cut: https://github.com/schemedoc/implementation-metadata/pull/5

**Comment by lassik** [comment]
Added in #5
