### ISSUE TITLE
gerbil is missing

### ISSUE THREAD

**Issue by vyzo** [schemedoc/implementation-metadata#4]
https://github.com/vyzo/gerbil

**Comment by lassik** [comment]
Are you the author of Gerbil? Great project! Thanks for interest in this :) Do you have time to make a PR for Gerbil? Just take an existing one like `chicken.scm` and edit the URLs.

**Comment by FrankRuben** [comment]
Btw.: Not (yet) in the metadata-repo, but Gerbil is already listed in the SRFI-collector: [https://github.com/schemedoc/implementation-metadata/blob/master/tools/Scheme_SRFIs.md](https://github.com/schemedoc/implementation-metadata/blob/master/tools/Scheme_SRFIs.md), data collection is here: [https://github.com/schemedoc/implementation-metadata/blob/master/tools/Create_Scheme_SRFIs.org](https://github.com/schemedoc/implementation-metadata/blob/master/tools/Create_Scheme_SRFIs.org).

**Comment by lassik** [comment]
Added Gerbil in commit d53bfe5. The new implementations are taking very interesting approaches!
